export const COMPONENT = {
  Application: Symbol.for('Application'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  UserModel: Symbol.for('UserModel'),
  OfferModel: Symbol.for('OfferModel'),
  CommentModel: Symbol.for('CommentModel'),
  FavoriteModel: Symbol.for('FavoriteModel'),
  UserRepositoryInterface: Symbol.for('UserRepositoryInterface'),
  OfferRepositoryInterface: Symbol.for('OfferRepositoryInterface'),
  CommentRepositoryInterface: Symbol.for('CommentRepositoryInterface'),
  FavoriteRepositoryInterface: Symbol.for('FavoriteRepositoryInterface'),
  UserService: Symbol.for('UserService'),
  OfferService: Symbol.for('OfferService'),
  CommentService: Symbol.for('CommentService'),
  FavoriteService: Symbol.for('FavoriteService'),
} as const;
